# file: tasks/clustercheck.yml

- name: Copy clustercheck script
  template:
    src: "usr/bin/clustercheck.j2"
    dest: "/usr/bin/clustercheck"
    owner: "root"
    group: "root"
    mode: "0700"

- name: Copy clustercheck script
  template:
    src: "usr/local/bin/pyclustercheck.j2"
    dest: "/usr/local/bin/pyclustercheck"
    owner: "root"
    group: "root"
    mode: "0700"

- name: Append clustercheck to services 
  lineinfile:
    dest: /etc/services
    regexp: "^mysqlchk"
    line: "mysqlchk        9200/tcp"
    state: present
  notify: restart xinetd

- name: Add xinetd services
  copy:
    src: "etc/xinetd.d/mysqlchk"
    dest: "/etc/xinetd.d/mysqlchk"
    mode: "u=rw,g=r,o=r"
  notify: restart xinetd

